zone:
  name: "domain.tld" # your OVH registered domain
  subdomain: "subdomain" # subdomain whose dns record to update
  user: "domain.tld-id" # authentication user-id you set
  password: "changeme" # the corresponding password